### ISSUE TITLE
Reconnect error

### ISSUE THREAD

**Issue by ZipfSebastian** [balazshorvath/NorocBackend#15]
When i reconnect to server i become this error, and i can't connect.

Exception in thread "Thread-21" java.lang.NullPointerException
    at java.io.StringReader.<init>(StringReader.java:50)
    at org.codehaus.jackson.JsonFactory.createJsonParser(JsonFactory.java:636)
    at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1863)
    at hu.noroc.entry.network.GamingClient.run(GamingClient.java:83)
    at java.lang.Thread.run(Thread.java:745)

**Comment by balazshorvath** [comment]
The reconnection feature is ready, waiting for testing

**Comment by ZipfSebastian** [comment]
![reconnecterror](https://cloud.githubusercontent.com/assets/14239218/14936820/0858eed2-0ef6-11e6-8189-9984feb93b8c.png)

After login, pause, reconnect i become not authenticated error than empty responses for infinity
u can see the process on this pic.

**Comment by balazshorvath** [comment]
Unit tests now include reconnect feature test.
Tests run green now.
